workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    openapi.json:
        inputs:
            - location: https://api.unkey.dev/openapi.json
        registry:
            location: registry.speakeasyapi.dev/unkey/unkey/openapi-json
targets:
    go:
        target: go
        source: openapi.json
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/unkey/unkey/openapi-json-code-samples
            blocking: false
